### ISSUE TITLE
First DM in list appears squashed/small

### ISSUE THREAD

**Issue by logan-0712** [blueb442/purpura#7]
**Describe the bug**
When using this theme, the first DM in the list appears smaller than it should

**Where is it?**
DM list

**Screenshots**
[Screenshot](https://cdn.discordapp.com/attachments/452583282845155342/975778487694667826/unknown.png?size=4096)

**Version**
 - OS: Windows 10 Home
 - Theme: Latest version of Purpura downloaded [from betterdiscord](https://betterdiscord.app/theme/Purpura)

**Other Information**
It doesn't seem to be a zoom issue. I've tried zooming out and it stays consistent.

**Comment by blueb442** [comment]
This issue is from the way I've styled the buttons, they aren't easy. It's supposed to look like it does in my screenshot, but I didn't select the items in a smart way. For now I'll remove it, and I might not add it back.
![image](https://user-images.githubusercontent.com/76005739/168781195-30ca6448-6592-43cf-aee5-a4659925e677.png)
